# Created by @KefreR (Frank Ressat)

import sqlite3
from scripts.ilapfuncs import logfunc, logdevinfo, timeline, kmlgen, tsv, is_platform_windows, open_sqlite_db_readonly

def get_twint(files_found, report_folder, seeker, wrap_text):
    for file_found in files_found:
        file_found = str(file_found)

    data_list = []
    db = open_sqlite_db_readonly(file_found)
    cursor = db.cursor()
    cursor.execute('''
         SELECT 
         ZTRANSACTION.Z_PK as "INDEX",
         datetime(ZTRANSACTION.ZCREATIONDATE+978307200,'UNIXEPOCH', 'LOCALTIME') as "CREATION DATE",
         datetime(ZTRANSACTION.ZMODIFIEDTIMESTAMP+978307200,'UNIXEPOCH', 'LOCALTIME') as "APPLICATION VALIDATION DATE", 
         datetime(ZTRANSACTION.ZSECONDPHASETIMESTAMP+978307200,'UNIXEPOCH', 'LOCALTIME') as "SECOND PHASE TIMESTAMP (DESTINATION VALIDATION)", 
         datetime(ZTRANSACTION.ZSTATUSPENDINGUNTILDATE+978307200,'UNIXEPOCH', 'LOCALTIME') as "TRANSACTION EXPIRY DATE", 
         ZTRANSACTION.ZMERCHANTBRANCHNAME as "MERCHANT BRANCH NAME", ZTRANSACTION.ZMERCHANTNAME as "MERCHANT NAME", 
         ZTRANSACTION.ZP2PSENDERMOBILENR as "SENDER MOBILE NUMBER", 
         ZTRANSACTION.ZP2PINITIATEMESSAGE as "INITIATE MESSAGE OF TRANSACTION", 
         ZTRANSACTION.ZP2PRECIPIENTMOBILENR as "RECIPIENT MOBILE NUMBER", 
         ZTRANSACTION.ZP2PRECIPIENTNAME as "RECIPIENT NAME", 
         ZTRANSACTION.ZP2PREPLYMESSAGE as "REPLY MESSAGE", 
         ZTRANSACTION.ZCONTENTREFERENCE as "CONTENT REFERENCE", 
         ZTRANSACTION.ZAUTHORIZEDAMOUNT as "AUTHORIZED AMOUNT", 
         ZTRANSACTION.ZPAIDAMOUNT as "PAID AMOUNT", 
         ZTRANSACTION.ZREQUESTEDAMOUNT as "REQUESTED AMOUNT", 
         ZTRANSACTION.ZDISCOUNT as "DISCOUNT", 
         ZTRANSACTION.ZCURRENCY as "CURRENCY", 
         ZTRANSACTION.ZORDERLINK as "ORDER LINK", 
         ZTRANSACTION.ZCONTENTREFERENCESOURCEVALUE as "CONTENT REF SOURCE VALUE", 
         ZTRANSACTION.ZORDERSTATEVALUE as "TRANSACTION STATE", 
         ZTRANSACTION.ZORDERTYPEVALUE as "TRANSACTION TYPE", 
         ZTRANSACTION.ZP2PHASPICTURE as "PRESENCE OF PICTURE IN TRANSACTION", 
         ZTRANSACTION.ZTRANSACTIONSIDEVALUE as "TRANSACTION ID VALUE", 
         ZTRANSACTION.ZFAILUREREASON as "TECHNICAL FAILURE REASON", 
         ZTRANSACTION.ZIBAN as "IBAN", 
         ZTRANSACTION.ZMERCHANTTRANSACTIONREF as "MERCHANT TRANSACTION REF", 
         ZTRANSACTION.ZORDERUUIDSTRING as "ORDER UUID" FROM ZTRANSACTION''')


__artifacts__ = {
    "twint": (
        "Twint",
        ('var/mobile/Containers/Data/Application/*/Library/Application Support/Twint.sqlite'),
        get_twint)
}